import React from 'react';
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  Cell
} from 'recharts';

export function StatusChart({ statusCodes, statusCategories }) {
  if (!statusCodes || statusCodes.length === 0) return null;

  // Assign colors based on HTTP status code class
  const getStatusColor = (codeStr) => {
    const code = parseInt(codeStr, 10);
    if (code >= 200 && code < 300) return '#10B981'; // Emerald
    if (code >= 300 && code < 400) return '#3B82F6'; // Blue
    if (code >= 400 && code < 500) return '#F59E0B'; // Amber
    if (code >= 500) return '#EF4444'; // Red
    return '#8B5CF6';
  };

  const CustomTooltip = ({ active, payload, label }) => {
    if (active && payload && payload.length) {
      const count = payload[0].value;
      return (
        <div className="p-3 rounded-lg bg-gray-900 border border-gray-700 shadow-xl text-xs">
          <div className="font-bold text-white flex items-center gap-2">
            <span
              className="w-2.5 h-2.5 rounded-full"
              style={{ backgroundColor: getStatusColor(label) }}
            />
            <span>HTTP {label}</span>
          </div>
          <div className="text-gray-300 mt-1 font-mono">
            {count.toLocaleString()} requests
          </div>
        </div>
      );
    }
    return null;
  };

  const totalCatRequests = statusCategories
    ? statusCategories.reduce((acc, curr) => acc + (curr.count || 0), 0)
    : 0;

  return (
    <div className="p-5 rounded-xl bg-[#111827] border border-gray-800 space-y-5">
      <div>
        <h3 className="text-sm font-bold text-white">
          HTTP Status Codes Distribution
        </h3>
        <p className="text-xs text-gray-400 mt-0.5">
          Detailed response codes generated by the web server (only statuses present in the data are displayed).
        </p>
      </div>

      {/* Category Summary Badges (Section 11) */}
      {statusCategories && statusCategories.length > 0 && (
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          {statusCategories.map((cat) => {
            const pct = totalCatRequests > 0 ? ((cat.count / totalCatRequests) * 100).toFixed(1) : 0;
            return (
              <div
                key={cat.key}
                className="p-3 rounded-xl bg-gray-900/80 border border-gray-800 flex flex-col justify-between"
              >
                <div className="flex items-center justify-between text-xs text-gray-400 mb-1">
                  <span>{cat.category}</span>
                  <span className="font-mono text-gray-400">{pct}%</span>
                </div>
                <div className="text-lg font-bold text-white font-mono">
                  {cat.count.toLocaleString()}
                </div>
                {/* Progress bar */}
                <div className="w-full h-1.5 bg-gray-800 rounded-full mt-2 overflow-hidden">
                  <div
                    className="h-full rounded-full transition-all duration-500"
                    style={{
                      width: `${pct}%`,
                      backgroundColor: cat.color || '#6366F1'
                    }}
                  />
                </div>
              </div>
            );
          })}
        </div>
      )}

      {/* Bar Chart */}
      <div className="h-64 w-full pt-2">
        <ResponsiveContainer width="100%" height="100%">
          <BarChart data={statusCodes} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
            <CartesianGrid strokeDasharray="3 3" stroke="#1F2937" vertical={false} />
            <XAxis dataKey="code" stroke="#6B7280" fontSize={11} tickLine={false} />
            <YAxis stroke="#6B7280" fontSize={11} tickLine={false} axisLine={false} />
            <Tooltip content={<CustomTooltip />} />
            <Bar dataKey="count" radius={[4, 4, 0, 0]}>
              {statusCodes.map((entry, index) => (
                <Cell key={`cell-${index}`} fill={getStatusColor(entry.code)} />
              ))}
            </Bar>
          </BarChart>
        </ResponsiveContainer>
      </div>
    </div>
  );
}
